// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4, arg5);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function State() {
  return window['go']['main']['App']['State']();
}
