// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['main']['App']['About']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CloseToTray(arg1) {
  return window['go']['main']['App']['CloseToTray'](arg1);
}

export function ExitApp(arg1) {
  return window['go']['main']['App']['ExitApp'](arg1);
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkFrontendReady() {
  return window['go']['main']['App']['MarkFrontendReady']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function State() {
  return window['go']['main']['App']['State']();
}
