// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function About():Promise<main.AboutInfo>;

export function CheckUpdate():Promise<main.UpdateInfo>;

export function CloseToTray(arg1:boolean):Promise<void>;

export function ExitApp(arg1:boolean):Promise<void>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function Logout():Promise<void>;

export function MarkFrontendReady():Promise<void>;

export function Refresh():Promise<main.AppState>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function Settings():Promise<config.Settings>;

export function State():Promise<main.AppState>;
